import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "../public/css/tailwind.css"
import 'bootstrap-icons/font/bootstrap-icons.css';

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ['200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${roboto.className} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
