import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/context/queryProvider";
import { GlobalProvider } from "@/context/globalProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`font-sans`}
            >
                <QueryProvider>
                    <GlobalProvider>
                        {children}
                    </GlobalProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
