import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../public/tailwind.css"
import ReactQueryProvider from "@/context/QueryProvider";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ['200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
    title: "Ecom Products",
    description: "Generated by Ecom Products",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} antialiased`}
            >
                <ReactQueryProvider>
                    {children}
                </ReactQueryProvider>
            </body>
        </html>
    );
}
