import type { Metadata } from "next";
import { Roboto, Raleway, Inter } from "next/font/google";

import "./globals.css"; const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ['200', '300', '400', '500', '600', '700', '800', '900']
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ['200', '300', '400', '500', '600', '700', '800', '900']
});

const raleway = Raleway({
    variable: "--font-raleway",
    subsets: ["latin"],
    weight: ['200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" style={{ scrollBehavior: 'smooth' }}>
            <body
                className={`${roboto.className} ${raleway.className} ${inter.className} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
